on: push

jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WORKING DIRECTORY
        run: pwd  
  building:
    runs-on: ubuntu-latest
    needs: [checking]
    steps:
      - uses: actions/checkout@v2
      - name: WORKING DIRECTORY
        run: pwd  

