on: push

jobs:

  testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: WORKING DIRECTORY
          run: pwd

        - name: INSTALL GCC
          run: |
            sudo apt-get update && sudo apt-get install -y gcc g++
            which gcc
        - name: INSTALL CMAKE
          run: |
            sudo apt-get update && sudo apt-get install -y cmake
            which cmake
        - name: INSTALL LCOV
          run: |
            sudo apt-get update && sudo apt-get install -y lcov
            which lcov
        - name: INSTALL GTEST
          run:  |
            git clone https://github.com/google/googletest
            pwd
            cd ./googletest
            pwd
            mkdir -p build && cd build
            sudo cmake ..
            sudo make
            sudo make install
            cd ../../
            pwd
        - name: INPUT_TEST
          run:  |
            cd v1
            mkdir -p build && cd build
            sudo cmake ..
            sudo make
            ./v1
            cd tests
            sudo ./test_vec
            cd ../
            cat result.txt
            cat time1.txt
        - name: INPUT_TEST2
          run:  |
            cd v2
            mkdir -p build && cd build
            sudo cmake ..
            sudo make
            ./v2
            cd tests_lib2
            sudo ./test_vec2
            cd ../
            cat result.txt
            cat time2.txt
          